#!/usr/bin/env sh

set -eu

main() {
	local REPO='https://github.com/folke/tokyonight.nvim.git'
	local REPO_NAME='tokyonight.nvim/'
	local THEME_DIR='extras/sublime/'

	type bat >/dev/null 2>&1
	local BAT_THEMES_DIR="$(command bat --config-dir)/themes"
	local BAT_THEME_CACHE="$(command bat --cache-dir)/themes.bin"

	[ ! -d "$BAT_THEMES_DIR" ] && mkdir -p "$BAT_THEMES_DIR"
	cd "$BAT_THEMES_DIR"
	if [ ! -d "$REPO_NAME" ]; then
		git clone --depth=1 --filter=blob:none --sparse "$REPO"
		cd "$REPO_NAME"
		git sparse-checkout set "$THEME_DIR"
		# This doesn't prompt a user for confirmation.
		# Especially watch out for the "Valve Steam Cleaner" !
		# <https://www.theregister.com/2015/01/17/scary_code_of_the_week_steam_cleans_linux_pcs/>
		find "${BAT_THEMES_DIR:?}/${REPO_NAME:?}" -maxdepth 1 -type f -delete
	else
		cd "$REPO_NAME"
		git fetch
		local behind=$(git rev-list --count "HEAD..@{u}")
		if [ ${behind:?} != 0 ]; then
			# Show changings
			git -c core.pager='' log "HEAD..@{u}" --oneline
			git merge
		fi
	fi

	# Validate the cache, compare modification times
	if [ ! -d "$BAT_THEME_CACHE" ] \
	|| [ -n "$(find "$BAT_THEMES_DIR" -name '*.tmTheme' -newer "$BAT_THEME_CACHE")" ]; then
		command bat cache --build
	fi

	return 0
}

main
